
title: BagIt Research Data (BIRD) repository
email: r.oostenveld@gmail.com
description:
baseurl: ""
url: "https://robertoostenveld.github.io/bird/"

# Build settings
# theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:path
    
exclude:
  - README.md
  - Gemfile*
