Title: 'Taking common ground into account: Specifying the role of the mentalizing
  network in communicative language production'
Description: Several studies have shown that communicative language production as
  compared to non-communicative language production recruits parts of the mentalizing
  or theory of mind network, yet the exact role of this network in communication remains
  underspecified. In this study, we therefore aimed to test under what conditions
  the mentalizing network contributes to communicative language production. We were
  especially interested in distinguishing between situations in which speakers have
  to consider which information they do or do not share with their addressee (common
  vs. privileged ground information). We therefore manipulated whether speakers had
  to distinguish between common and privileged ground in order to communicate efficiently
  with the listener, in addition to comparing language production in a communicative
  and a non-communicative context. Participants performed a referential communicative
  game in the MRI-scanner as well as a similar, non-communicative task. We found that
  the medial prefrontal cortex, a core region of the mentalizing network, is especially
  sensitive to communicative contexts in which speakers have to take their addressee’s
  needs into account in order to communicate efficiently. In addition, we found neural
  differences between the communicative and the non-communicative settings before
  speakers started to plan their utterances, suggesting that they continuously update
  common ground in a communicative context.
CollectionIdentifier: di.dccn.DSC_3011038.02_274
PersistentIdentifier: 10.34973/56bj-vt72
PersistentURL: https://doi.org/10.34973/56bj-vt72
ProjectIdentifier: '3011038.02'
OrganisationalUnit: DCCN
Type: Data Sharing Collection
PreservationTime: '10'
State: Published
Publisher: Radboud University
DataUseAgreement: CC-BY-SA-4.0
EthicalApprovals: ''
FreeKeywords:
- 'theory of mind'
- 'mentalizing'
- 'language production'
- 'fMRI'
- 'communication'
SFNKeywords: ['']
MeSHKeywords: ['']
Version: '1'
AssociatedPublications: ''
AssociatedData: ''
AssociatedAnalysisTools: ''
AssociatedPreregistrations: ''
Authors:
- 'Flora Vanlangendonck'
- 'Willems, R.M.'
- 'Hagoort, P.'
Managers:
- 'Willems, R.M.'
- 'Hagoort, P.'
Contributors: ['Flora Vanlangendonck']
NumberOfFiles: '41255'
Size: '12140228477'
Quota: '154618822656'
CreationDate: 27-Sep-2018 10:07:04
LastUpdateDate: 08-Oct-2021 12:02:23
EmbargoUntil: 27-Sep-2018 10:07:04
PublicationDate: 27-Sep-2018 10:07:04
ArchivalDate: ''
ViewersByDUA: '3'
ViewersByManager: '0'
Views: '426'
Downloads: '470270'
DataVolume: '138267725140'
Viewers: '261'
Downloaders: '843'
